apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ .Values.name }}
  port:
    targetPort: {{ .Values.service.targetPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect