apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}  # Aseg√∫rate de que coincida con tu Deployment
spec:
  selector:
    app: {{ .Values.name }}  # Debe coincidir con las labels del Deployment
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port}}         # Puerto del Service
      targetPort: {{ .Values.service.targetPort}}  # Puerto del contenedor
  type: ClusterIP     # Cambia a NodePort o LoadBalancer si quieres acceso externo